pipeline {
   agent any

   stages {
      stage('Build') {
         steps {
             withEnv(["JAVA_HOME=${tool 'Java11'}","PATH+MAVEN=${tool 'Mvn3'}/bin:${env.JAVA_HOME}/bin"]) {

            // Get some code from a GitHub repository
            git 'https://github.com/Gerencser/day0tooling.git'

            sh "cd demo; mvn -V -Dmaven.test.skip=true clean compile package"
            }
         }
      }
      stage('CreateEnvironment') {
         steps {
             withCredentials(
                    [
                        string(credentialsId: 'accessid', variable: 'ACCESS_KEY'),
                        string(credentialsId: 'secret', variable: 'SECRET_ACCESS_KEY'),
                        string(credentialsId: 'dbpwd', variable: 'DB_USER_PWD')
                    ]
                ) {
               catchError {
                    sh '''
                        eval \$(ssh-agent -s);
                        ssh-add /home/tomcat/.ssh/aws;
                        cd demo/environment;
                        echo ${DB_USER_PWD}
                        /opt/terraform/terraform init;
                        #/opt/terraform/terraform refresh -var 'key_name=demo' -var 'public_key_path=/home/tomcat/.ssh/aws.pub' -var "accesskey=\$ACCESS_KEY" -var "secretaccesskey=\$SECRET_ACCESS_KEY" -var "db_user_pwd=\$DB_USER_PWD"
                        /opt/terraform/terraform apply -var 'key_name=demo' -var 'public_key_path=/home/tomcat/.ssh/aws.pub' -var "accesskey=\$ACCESS_KEY" -var "secretaccesskey=\$SECRET_ACCESS_KEY" -var "db_user_pwd=\$DB_USER_PWD" -auto-approve
                    '''
               }
               sh "sleep 60s"
            }
         }
      }
      stage('SetupEnvironment') {
         steps {
             withCredentials(
                    [
                        string(credentialsId: 'dbpwd', variable: 'DB_USER_PWD')
                    ]
                ) {
                sh '''
                    eval \$(ssh-agent -s);
                    ssh-add /home/tomcat/.ssh/aws;
                    cd demo/environment;
                    APPLICATION_HOST1=$(/opt/terraform/terraform output application_address1);
                    APPLICATION_HOST2=$(/opt/terraform/terraform output application_address2);
                    APPLICATION_HOS3$=$(/opt/terraform/terraform output application_address3);
                    DATABASE_HOST=$(/opt/terraform/terraform output database_address);
                    DB_URL=jdbc:mysql://10.0.1.200:3306/demodb;
                    cd ../target;
                    ssh ubuntu@\$APPLICATION_HOST1 "sudo pkill -f 'java'"
                    scp demo-0.0.1-SNAPSHOT.jar ubuntu@\$APPLICATION_HOST1:/home/ubuntu/demo.jar
                    ssh ubuntu@\$APPLICATION_HOST1 "nohup java -jar /home/ubuntu/demo.jar --spring.datasource.url=\$DB_URL > /dev/null 2>&1 &";
                    ssh ubuntu@\$APPLICATION_HOST2 "sudo pkill -f 'java'"
                    scp demo-0.0.1-SNAPSHOT.jar ubuntu@\$APPLICATION_HOST2:/home/ubuntu/demo.jar
                    ssh ubuntu@\$APPLICATION_HOST2 "nohup java -jar /home/ubuntu/demo.jar --spring.datasource.url=\$DB_URL > /dev/null 2>&1 &";
                    ssh ubuntu@\$APPLICATION_HOST3 "sudo pkill -f 'java'"
                    scp demo-0.0.1-SNAPSHOT.jar ubuntu@\$APPLICATION_HOST3:/home/ubuntu/demo.jar
                    ssh ubuntu@\$APPLICATION_HOST3 "nohup java -jar /home/ubuntu/demo.jar --spring.datasource.url=\$DB_URL > /dev/null 2>&1 &";
                '''
                }
         }
      }
      stage('PerformanceTest') {
         steps {
                sh '''
                    cd demo/environment;
                    ADDRESS1=$(/opt/terraform/terraform output address1);
                    cd ../performance
                    /opt/jmeter/bin/jmeter.sh -Jthreads=10000 -Jhostname=\$ADDRESS1 -n -t PerformanceTest.jmx -l result.jtl
                '''
         }
       }
         post {
                    success {
                      archiveArtifacts 'demo/performance/*.*'
                    }
                 }
   }
}